#!/bin/bash

id=$1
temp=$2
hum=$3
seq=$4
lowbatt=$5
rssi=$6
time=$8
url="https://HOST/api/get-values?item=$id&temp=$temp&humidity=$hum&lowbatt=$lowbatt&time=$time"

curl -H "Authorization: Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" $url